services:
  emitters:
    - http://65.21.235.219:9999/events/main
    - http://65.21.235.219:9999/events/deploys
    - http://65.21.235.219:9999/events/sigs
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: /var/log/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: 10.12.0.8:9092
    producer:
      client-id: stormeye-kafka-dev