services:
  emitters:
    - ${CASPER_EVENTS_MAIN:http://65.21.235.219:9999}
  topics:
    - topic: sigs
      partitions: 2
      replicas: 3
    - topic: deploys
      partitions: 3
      replicas: 5
    - topic: main
      partitions: 3
      replicas: 5
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: /var/log/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_SERVICE_HOST}:${KAFKA_SERVICE_SERVICE_PORT}
    producer:
      client-id: stormeye-kafka-dev