services:
  emitters:
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http//13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http//13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
server:
  port: 8080
spring:
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: ${KAFKA_CLIENT_ID:stormeye-kafka}
  application:
    name: Casper Event Store Kafka Producer
