services:
  emitters:
    - http://65.21.235.219:9999/events/main
    - http://65.21.235.219:9999/events/deploys
    - http://65.21.235.219:9999/events/sigs
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: ${HOME}/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: stormeye-kafka-local