services:
  emitters:
    - http://65.21.235.219:9999/events/main
    - http://65.21.235.219:9999/events/deploys
    - http://65.21.235.219:9999/events/sigs
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: /var/log/cspr-producer.log
spring:
  kafka:
#    bootstrap-servers: http://10.16.11.130:9092
    bootstrap-servers: ${KAFKA_SERVICE_SERVICE_HOST}:${KAFKA_SERVICE_SERVICE_POST}
    producer:
      client-id: stormeye-kafka-dev