services:
  emitters:
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
    - http://13.41.171.131:8082/test-emitter/events/main
    - http://13.41.171.131:8082/test-emitter/events/deploys
    - http://13.41.171.131:8082/test-emitter/events/sig
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: /var/log/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: 172.31.8.239:9092
    producer:
      client-id: stormeye-kafka-dev