services:
   topics:
    - topic: sigs
      partitions: 2
      replicas: 3
    - topic: deploys
      partitions: 3
      replicas: 5
    - topic: main
      partitions: 3
      replicas: 5
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: /var/log/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: 172.31.8.239:9092
    producer:
      client-id: stormeye-kafka-dev