logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: ${HOME}/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: stormeye-kafka-local