services:
  emitters:
    - ${CASPER_EVENTS_MAIN:http://65.21.235.219:9999/events/main}
    - ${CASPER_EVENTS_DEPLOYS:http://65.21.235.219:9999/events/deploys}
    - ${CASPER_EVENTS_SIGS:http://65.21.235.219:9999/events/sigs}
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
server:
  port: 8080
spring:
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: ${KAFKA_CLIENT_ID:stormeye-kafka}
  application:
    name: Casper Event Store Kafka Producer
