services:
  topics:
    - topic: sigs
      partitions: 2
      replicas: 3
    - topic: deploys
      partitions: 3
      replicas: 5
    - topic: main
      partitions: 3
      replicas: 5
  emitters:
    - ${CASPER_EVENTS_MAIN:http://65.21.235.219:9999}
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:DEBUG}
  file:
    name: ${HOME}/cspr-producer.log
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: stormeye-kafka-local
